language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: yan-ecommerce
  api_key:
    secure: n95Ay8kKfcn1aYRYz1ThqJMqgsYOrLlXN+zzCJPA5hSY1CuGWgwGTGn2SH3M2NGe39hrVTf7rsEvYYYamCOxsiBih+lAkvXxd9yFITgxiPiI/IukHYk8RlEGce6IgI2HCo+3nfK3sMhxgDZiV6unW/66EEcOQpYhnHH+tKi8YJYHqbtk+DkAh1YirMQJqxsnTLWR8+2aemMhdOQgTq/Zpx3AWBhU7VuOSPz1Kl/kOdc3YxGGzo6fH5gV5XyXir/Rk9c0a2MVmc5BnXaXAH5UVFYJsza4rAfaiJRsh4AotgcJOgM2PXZSye0SC61ncB9aZjr6Xmk1usnh3iGwYM0RrMOM9ht/D55KCLqLYSaov7ZCoipDGIFgcmddv1/4aV0gUfgI+DXr1qHPv0qkaRJ/V1y0yEMweMdICF4CpR1s/8L1rqwNsERdglth8GY32abAoODQ7TWZkQ/NCQ4uuj7FKRi2pmvN94KOMQlKyIAXH0SySZDt1/+uJdpDJzDYozkBiCmcmMhKDoY7HVhKuuSR5pBEKtLGT9y24gPW6J5Dc5eROUHvBaz7v4kESGbNIenRTLdlRjcdZqn0bFXco5l12UMC4KElA/G03exjcDTjyS9avAToe6X8FBmY+INLMSzqBpimXHO6TPgEYdCrT1/5KVdHobuckqDJq3IITtpF4xA=
