language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: yan-ecommerce
  api_key:
    secure: oXpMu/ZUM52pFLOrSBHf9ubdazKLT5qnWHZTH9y7En0+NSYEKD1RJPyc0Zm0pLYxUXU/pXIl/aKod3S3xGGnw3H7nKowZTAFRfblUWKAgFoVSqPTMiTICpEak8YQbN8Dtaf38MaX4oR7K7mcmA8j0sy8oB/jDbf6nXdpo/i7rmFQXavCHDLy1J38GwCt+OOIKoMER00TrOOnyOI9apH+iqsQDD0wx2dYFc56XO0yznPZFC2i65WHfM2l/m6hwORNuR5OzjbwRZP3ermjfhfnRA+PqzYEBBiycexn+4EHUvf5eDImlZxlS4juEzhCe/HgNzeB4k27ImQn526pg2HlkXPmOz+pSmsZDqFAcyTgE1eTG2wEkE6fvbTzZ9pll1Zlm6RhmG21XT5FTv9fC1oqByrADu6zGJxZI6QffMWwUBB56yw8rGAGHcuA5lku0iqww7UIZsraBcwYfx7sWz5+b3U8utklYYZ11BVyFv9FS07GcD4PKwMC+1jw/uQtqI6EG9io2O5PbdcZFkSAtjOi2szw5tUa/Q58+Qwynug7UVFTBLlhKhZz/OizwrRlreOGMbm/TRRBGTsZpVxcTCU6P389L1Gz7c4a9NGZjzK2e8BJQA/YNVRosym4aCiJ9Z3cpgs3dTyYnB5xVOpvHDF7TAfQB8GvxcbaNwlB1GACK90=
