language: node_js
node_js:
  - "12"
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  app: yan-ecommerce
  api_key:
    secure: KSj15I20dLCzgFvQ0UcWcEWm38tibWXz9cK9J33g99kURlouTAwPX0XFieUk8gTyvdXv8KXIxV0eLYOCTd/CKzIyp8NZYnlHAw5Kh03Qh2TZadtQZBBexUoA8rnqnLbXLRP4O50izgeLkos+xGcoB81zrZDytveWqntxzuG4kzXuZ6kc7JmDNbT1LZZN/EBm/UByb5WRlxooxpSNBruMAHCgzgnYJ7mdz3TkAD1wOdIBF+hfXtgRtD0OKMOkPXTnM/1F+KIUUfYTfMoUVCqLWu9O00sq53emUwY4HSlY1T6tDsTa1KV6nKHwTqPTpjIHnmJtdp322woQQVCsRrCqCytq+MYIAhSYcyK88PQT7DHDJBBSHbQhY8Gw2Ec9nbY0WnxPX9mg1CFhnwqUCdfamwDVZJIOW16BRdI4ccm68JHrZXXxK+Ua3cR9HXyJDoJDohW7/1JWHv2MYpTb1UhSoSRlFPYHpvRoo/kNcvgeDpoAIVOPgtxAd4H67i47W1S/IIceOXAy8pSDYrOAHGfdPvTOaKTHLaUBGnCuRUjA+gq1JYjS5cb2DQnsl+hZPcNK5yMh1xOxUcst+dgSc6kQyvUXseycAfe02px197wRjkI2Vlc6zD5B30IIbKYEZ+YoFZyHk/Rh4OUMXyOmYPf/4OU6rIjbsB+ZGL9MHdSI4Q0=
